# Generated by Django 3.0.4 on 2021-07-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Cart')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.Service')),
            ],
        ),
    ]
