# Generated by Django 3.0.4 on 2021-07-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_auto_20210730_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
    ]
